steps: 

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: build
  args: [
    'build',
    '-f',
    'Dockerfile.prod',
    '-t',
    'gcr.io/counselling-website-341817/counselling-app-image:$COMMIT_SHA',
    '.',
    "--build-arg",
    "RECAPTCHA_KEY=${_RECAPTCHA_KEY}",
    "--build-arg",
    "RECAPTCHA_URL=${_RECAPTCHA_URL}",
    "--build-arg",
    "MAIL_HOST=${_MAIL_HOST}",
    "--build-arg",
    "MAIL_PASS=${_MAIL_PASS}",
    "--build-arg",
    "PUBLIC_EMAIL_ADDRESS=${_PUBLIC_EMAIL_ADDRESS}",
    "--build-arg",
    "PUBLIC_PHONE_NUMBER=${_PUBLIC_PHONE_NUMBER}",
    "--build-arg",
    "PUBLIC_PROFESSIONAL_NAME=${_PUBLIC_PROFESSIONAL_NAME}",
    "--build-arg",
    "PUBLIC_RECAPTCHA_KEY=${_PUBLIC_RECAPTCHA_KEY}"
  ]

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: push
  args: ['push', 'gcr.io/counselling-website-341817/counselling-app-image:$COMMIT_SHA']
  waitFor: ['build']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: deploy
  entrypoint: gcloud
  args: ['run', 'deploy', 'counselling-website', '--image', 'gcr.io/counselling-website-341817/counselling-app-image:$COMMIT_SHA', '--region', 'europe-west1', '--platform', 'managed', --allow-unauthenticated]
  waitFor: ['push']
images:
- gcr.io/counselling-website-341817/counselling-app-image:$COMMIT_SHA
