steps:

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: build
  args: ['build', '-t', 'gcr.io/counselling-website-341817/latest-image', '.']
  waitFor: ['-']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: push
  args: ['push', 'gcr.io/counselling-website-341817/latest-image']
  waitFor: ['build']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: deploy
  entrypoint: gcloud
  args: ['run', 'deploy', 'counselling-app', '--image', 'gcr.io/counselling-website-341817/latest-image', '--region', 'europe-west1', '--platform', 'managed']
  waitFor: ['build','push']
images:
  - gcr.io/counselling-website-341817/latest-image
